import Head from "next/head";
import React from "react";
import NavigationComponent from "./Nav.component";

type LayoutProps = {
  children: JSX.Element | string;
  page?: string;
};
const LayoutComponent: React.FC<LayoutProps> = ({ children, page }) => {
  return (
    <>
      <Head>
        <title>English Bootcamp</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavigationComponent />
      <div className='flex flex-col items-center justify-center min-h-max mx-auto px-6'>
        {children}
      </div>
    </>
  );
};

export default LayoutComponent;
